perfil:
    resource: "@PerfilBundle/Resources/config/routing.yml"
    prefix:   /perfil

administracion:
    resource: "@AdministracionBundle/Resources/config/routing.yml"
    prefix:   /admin

comun:
    resource: "@ComunBundle/Resources/config/routing.yml"
    prefix:   /
sitio:
    resource: "@SitioBundle/Resources/config/routing.yml"
    prefix:   /

change_pass:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile
fos_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /registration
#fos_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group