parameters:
#    sitio.example.class: COdigos\SitioBundle\Example

services:
#    sitio.example:
#        class: %sitio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
